create table  IF NOT EXISTS client_transport_report (
	serviceid	VARCHAR(255)	not null,
	mediaunitid	VARCHAR(255)	not null,
	timestamp	BIGINT	not null,
	callid	CHAR(36)	not null,
	clientid	CHAR(36)	not null,
	peerconnectionid	CHAR(36)	not null,
	bytesreceived	BIGINT,
	bytessent	BIGINT,
	candidatepairavailableincomingbitrate	REAL,
	candidatepairavailableoutgoingbitrate	REAL,
	candidatepairbytesdiscardedonsend	BIGINT,
	candidatepairbytesreceived	BIGINT,
	candidatepairbytessent	BIGINT,
	candidatepaircircuitbreakertriggercount	INTEGER,
	candidatepairconsentexpiredtimestamp	BIGINT,
	candidatepairconsentrequestbytessent	BIGINT,
	candidatepairconsentrequestssent	INTEGER,
	candidatepaircurrentroundtriptime	REAL,
	candidatepairfirstrequesttimestamp	BIGINT,
	candidatepairlastpacketreceivedtimestamp	BIGINT,
	candidatepairlastpacketsenttimestamp	BIGINT,
	candidatepairlastrequesttimestamp	BIGINT,
	candidatepairlastresponsetimestamp	BIGINT,
	candidatepairpacketsdiscardedonsend	INTEGER,
	candidatepairpacketsreceived	INTEGER,
	candidatepairpacketssent	INTEGER,
	candidatepairrequestbytessent	BIGINT,
	candidatepairrequestsreceived	INTEGER,
	candidatepairrequestssent	INTEGER,
	candidatepairresponsebytessent	BIGINT,
	candidatepairresponsesreceived	INTEGER,
	candidatepairresponsessent	INTEGER,
	candidatepairretransmissionreceived	INTEGER,
	candidatepairretransmissionsent	INTEGER,
	candidatepairstate	VARCHAR(255),
	candidatepairtotalroundtriptime	REAL,
	dtlscipher	VARCHAR(65535),
	dtlsstate	VARCHAR(255),
	icelocalusernamefragment	VARCHAR(65535),
	icerole	VARCHAR(65535),
	icetransportstate	VARCHAR(255),
	label	VARCHAR(65535),
	localaddress	VARCHAR(65535),
	localcandidateiceserverurl	VARCHAR(65535),
	localcandidaterelayprotocol	VARCHAR(255),
	localcandidatetype	VARCHAR(65535),
	localport	INTEGER,
	localprotocol	VARCHAR(255),
	marker	VARCHAR(65535),
	packetsreceived	INTEGER,
	packetssent	INTEGER,
	remoteaddress	VARCHAR(65535),
	remotecandidateiceserverurl	VARCHAR(65535),
	remotecandidaterelayprotocol	VARCHAR(255),
	remotecandidatetype	VARCHAR(65535),
	remoteport	INTEGER,
	remoteprotocol	VARCHAR(255),
	roomid	VARCHAR(255),
	sctpcongestionwindow	REAL,
	sctpmtu	INTEGER,
	sctpreceiverwindow	REAL,
	sctpsmoothedroundtriptime	REAL,
	sctpunackdata	INTEGER,
	selectedcandidatepairchanges	INTEGER,
	srtpcipher	VARCHAR(65535),
	tlsgroup	VARCHAR(65535),
	tlsversion	VARCHAR(65535),
	userid	VARCHAR(255)
) diststyle even;
ALTER TABLE client_transport_report ALTER diststyle KEY DISTKEY serviceid;
ALTER TABLE client_transport_report ALTER COMPOUND SORTKEY (callid, clientid, peerconnectionid);