create table  IF NOT EXISTS ice_candidate_pair_report (
	serviceid	VARCHAR(255)	not null,
	mediaunitid	VARCHAR(255)	not null,
	timestamp	BIGINT	not null,
	callid	CHAR(36)	not null,
	clientid	CHAR(36)	not null,
	peerconnectionid	CHAR(36)	not null,
	sampleseq	INTEGER	not null,
	availableincomingbitrate	REAL,
	availableoutgoingbitrate	REAL,
	bytesdiscardedonsend	BIGINT,
	bytesreceived	BIGINT,
	bytessent	BIGINT,
	consentrequestssent	INTEGER,
	currentroundtriptime	REAL,
	label	VARCHAR(65535),
	lastpacketreceivedtimestamp	BIGINT,
	lastpacketsenttimestamp	BIGINT,
	localcandidateid	VARCHAR(255),
	marker	VARCHAR(65535),
	nominated	BOOLEAN,
	packetsdiscardedonsend	INTEGER,
	packetsreceived	INTEGER,
	packetssent	INTEGER,
	remotecandidateid	VARCHAR(255),
	requestsreceived	INTEGER,
	requestssent	INTEGER,
	responsesreceived	INTEGER,
	responsessent	INTEGER,
	roomid	VARCHAR(255),
	state	VARCHAR(255),
	totalroundtriptime	REAL,
	transportid	CHAR(36),
	userid	VARCHAR(255)
) diststyle even;
ALTER TABLE ice_candidate_pair_report ALTER diststyle KEY DISTKEY serviceid;
ALTER TABLE ice_candidate_pair_report ALTER COMPOUND SORTKEY (callid, clientid, peerconnectionid, transportid);