create table  IF NOT EXISTS ice_candidate_pair_report (
	serviceid	VARCHAR(255)	not null,
	mediaunitid	VARCHAR(255)	not null,
	timestamp	BIGINT	not null,
	callid	CHAR(36)	not null,
	clientid	CHAR(36)	not null,
	peerconnectionid	CHAR(36)	not null,
	availableincomingbitrate	REAL,
	availableoutgoingbitrate	REAL,
	bytesdiscardedonsend	BIGINT,
	bytesreceived	BIGINT,
	bytessent	BIGINT,
	circuitbreakertriggercount	INTEGER,
	consentexpiredtimestamp	BIGINT,
	consentrequestbytessent	BIGINT,
	consentrequestssent	INTEGER,
	currentroundtriptime	REAL,
	firstrequesttimestamp	BIGINT,
	label	VARCHAR(65535),
	lastpacketreceivedtimestamp	BIGINT,
	lastpacketsenttimestamp	BIGINT,
	lastrequesttimestamp	BIGINT,
	lastresponsetimestamp	BIGINT,
	marker	VARCHAR(65535),
	packetsdiscardedonsend	INTEGER,
	packetsreceived	INTEGER,
	packetssent	INTEGER,
	requestbytessent	BIGINT,
	requestsreceived	INTEGER,
	requestssent	INTEGER,
	responsebytessent	BIGINT,
	responsesreceived	INTEGER,
	responsessent	INTEGER,
	retransmissionreceived	INTEGER,
	retransmissionsent	INTEGER,
	roomid	VARCHAR(255),
	state	VARCHAR(255),
	totalroundtriptime	REAL,
	userid	VARCHAR(255)
) diststyle even;
ALTER TABLE ice_candidate_pair_report ALTER diststyle KEY DISTKEY serviceid;
ALTER TABLE ice_candidate_pair_report ALTER COMPOUND SORTKEY (callid, clientid, peerconnectionid);