create table  IF NOT EXISTS inbound_video_track_report (
	serviceid	VARCHAR(255)	not null,
	mediaunitid	VARCHAR(255)	not null,
	timestamp	BIGINT	not null,
	callid	CHAR(36)	not null,
	clientid	CHAR(36)	not null,
	peerconnectionid	CHAR(36)	not null,
	sampleseq	INTEGER	not null,
	ssrc	BIGINT	not null,
	bytesreceived	BIGINT,
	bytessent	BIGINT,
	decoderimplementation	VARCHAR(65535),
	estimatedplayouttimestamp	BIGINT,
	fecpacketsdiscarded	INTEGER,
	fecpacketsreceived	INTEGER,
	fircount	INTEGER,
	frameheight	INTEGER,
	framesdecoded	INTEGER,
	framesdropped	INTEGER,
	framespersecond	REAL,
	framesreceived	INTEGER,
	framewidth	INTEGER,
	headerbytesreceived	BIGINT,
	jitter	REAL,
	jitterbufferdelay	REAL,
	jitterbufferemittedcount	INTEGER,
	jitterbufferminimumdelay	REAL,
	jitterbuffertargetdelay	REAL,
	keyframesdecoded	INTEGER,
	label	VARCHAR(65535),
	lastpacketreceivedtimestamp	BIGINT,
	marker	VARCHAR(65535),
	nackcount	INTEGER,
	packetsdiscarded	INTEGER,
	packetslost	INTEGER,
	packetsreceived	INTEGER,
	packetssent	INTEGER,
	plicount	INTEGER,
	qpsum	BIGINT,
	remoteclientid	VARCHAR(255),
	remotepeerconnectionid	VARCHAR(255),
	remotetimestamp	BIGINT,
	remotetrackid	VARCHAR(255),
	remoteuserid	VARCHAR(255),
	reportssent	INTEGER,
	roomid	VARCHAR(255),
	roundtriptime	REAL,
	roundtriptimemeasurements	INTEGER,
	sfusinkid	CHAR(36),
	sfustreamid	CHAR(36),
	totaldecodetime	REAL,
	totalinterframedelay	REAL,
	totalprocessingdelay	REAL,
	totalroundtriptime	REAL,
	totalsquaredinterframedelay	REAL,
	trackid	CHAR(36),
	userid	VARCHAR(255)
) diststyle even;
ALTER TABLE inbound_video_track_report ALTER diststyle KEY DISTKEY serviceid;
ALTER TABLE inbound_video_track_report ALTER COMPOUND SORTKEY (callid, clientid, peerconnectionid, sfusinkid, sfustreamid, trackid);