create table  IF NOT EXISTS inbound_video_track_report (
	serviceid	VARCHAR(255)	not null,
	mediaunitid	VARCHAR(255)	not null,
	timestamp	BIGINT	not null,
	callid	CHAR(36)	not null,
	clientid	CHAR(36)	not null,
	peerconnectionid	CHAR(36)	not null,
	sampleseq	INTEGER	not null,
	ssrc	BIGINT	not null,
	averagertcpinterval	REAL,
	burstdiscardcount	INTEGER,
	burstdiscardrate	REAL,
	burstlosscount	INTEGER,
	burstlossrate	REAL,
	burstpacketsdiscarded	INTEGER,
	burstpacketslost	INTEGER,
	bytesreceived	BIGINT,
	bytessent	BIGINT,
	clockrate	INTEGER,
	decoderimplementation	VARCHAR(65535),
	ended	BOOLEAN,
	estimatedplayouttimestamp	BIGINT,
	fecpacketsdiscarded	INTEGER,
	fecpacketsreceived	INTEGER,
	fircount	INTEGER,
	framebitdepth	INTEGER,
	frameheight	INTEGER,
	framesdecoded	INTEGER,
	framesdropped	INTEGER,
	framespersecond	REAL,
	framesreceived	INTEGER,
	framewidth	INTEGER,
	fullframeslost	INTEGER,
	gapdiscardrate	REAL,
	gaplossrate	REAL,
	headerbytesreceived	BIGINT,
	jitter	REAL,
	jitterbufferdelay	REAL,
	jitterbufferemittedcount	INTEGER,
	keyframesdecoded	INTEGER,
	label	VARCHAR(65535),
	lastpacketreceivedtimestamp	BIGINT,
	marker	VARCHAR(65535),
	mimetype	VARCHAR(65535),
	nackcount	INTEGER,
	packetsdiscarded	INTEGER,
	packetsduplicated	INTEGER,
	packetsfaileddecryption	INTEGER,
	packetslost	INTEGER,
	packetsreceived	INTEGER,
	packetsrepaired	INTEGER,
	packetssent	INTEGER,
	partialframeslost	INTEGER,
	payloadtype	INTEGER,
	perdscppacketsreceived	INTEGER,
	plicount	INTEGER,
	qpsum	BIGINT,
	remoteclientid	VARCHAR(255),
	remotepeerconnectionid	VARCHAR(255),
	remotetimestamp	BIGINT,
	remotetrackid	VARCHAR(255),
	remoteuserid	VARCHAR(255),
	reportssent	INTEGER,
	roomid	VARCHAR(255),
	sdpfmtpline	VARCHAR(65535),
	sfusinkid	CHAR(36),
	sfustreamid	CHAR(36),
	slicount	INTEGER,
	totaldecodetime	REAL,
	totalinterframedelay	REAL,
	totalprocessingdelay	REAL,
	totalsquaredinterframedelay	REAL,
	trackid	CHAR(36),
	userid	VARCHAR(255)
) diststyle even;
ALTER TABLE inbound_video_track_report ALTER diststyle KEY DISTKEY serviceid;
ALTER TABLE inbound_video_track_report ALTER COMPOUND SORTKEY (callid, clientid, peerconnectionid, sfusinkid, sfustreamid, trackid);