create table  IF NOT EXISTS OutboundVideoTrackReport (
	serviceId	VARCHAR(255)	not null,
	mediaUnitId	VARCHAR(255)	not null,
	timestamp	BIGINT	not null,
	callId	CHAR(36)	not null,
	clientId	CHAR(36)	not null,
	peerConnectionId	CHAR(36)	not null,
	sampleSeq	INTEGER	not null,
	ssrc	BIGINT	not null,
	averageRtcpInterval	REAL,
	burstDiscardCount	INTEGER,
	burstDiscardRate	REAL,
	burstLossCount	INTEGER,
	burstLossRate	REAL,
	burstPacketsDiscarded	INTEGER,
	burstPacketsLost	INTEGER,
	bytesDiscardedOnSend	BIGINT,
	bytesSent	BIGINT,
	channels	INTEGER,
	clockRate	INTEGER,
	encodedFrameBitDepth	INTEGER,
	encodedFrameHeight	INTEGER,
	encodedFramesPerSecond	REAL,
	encodedFrameWidth	INTEGER,
	encoderImplementation	VARCHAR(65535),
	ended	BOOLEAN,
	fecPacketsSent	INTEGER,
	firCount	INTEGER,
	fractionLost	REAL,
	frameBitDepth	INTEGER,
	frameHeight	INTEGER,
	framesDiscardedOnSend	INTEGER,
	framesDropped	INTEGER,
	framesEncoded	INTEGER,
	framesPerSecond	REAL,
	framesSent	INTEGER,
	frameWidth	INTEGER,
	fullFramesLost	INTEGER,
	gapDiscardRate	REAL,
	gapLossRate	REAL,
	headerBytesSent	BIGINT,
	hugeFramesSent	INTEGER,
	jitter	REAL,
	keyFramesEncoded	INTEGER,
	label	VARCHAR(65535),
	lastPacketSentTimestamp	BIGINT,
	marker	VARCHAR(65535),
	mimeType	VARCHAR(65535),
	nackCount	INTEGER,
	packetsDiscarded	INTEGER,
	packetsDiscardedOnSend	INTEGER,
	packetsLost	INTEGER,
	packetsReceived	INTEGER,
	packetsRepaired	INTEGER,
	packetsSent	INTEGER,
	partialFramesLost	INTEGER,
	payloadType	INTEGER,
	perDscpPacketsSent	INTEGER,
	pliCount	INTEGER,
	qpSum	BIGINT,
	qualityLimitationDurationBandwidth	REAL,
	qualityLimitationDurationCPU	REAL,
	qualityLimitationDurationNone	REAL,
	qualityLimitationDurationOther	REAL,
	qualityLimitationReason	VARCHAR(65535),
	qualityLimitationResolutionChanges	INTEGER,
	relayedSource	BOOLEAN,
	reportsReceived	INTEGER,
	retransmittedBytesSent	BIGINT,
	retransmittedPacketsSent	INTEGER,
	rid	VARCHAR(65535),
	roomId	VARCHAR(255),
	roundTripTime	REAL,
	roundTripTimeMeasurements	INTEGER,
	sdpFmtpLine	VARCHAR(65535),
	sfuStreamId	CHAR(36),
	sliCount	INTEGER,
	targetBitrate	INTEGER,
	totalEncodedBytesTarget	BIGINT,
	totalEncodeTime	REAL,
	totalPacketSendDelay	REAL,
	totalRoundTripTime	REAL,
	trackId	CHAR(36),
	userId	VARCHAR(255),
)