create table  IF NOT EXISTS OutboundAudioTrackReport (
	serviceId	VARCHAR(255)	not null,
	mediaUnitId	VARCHAR(255)	not null,
	timestamp	BIGINT	not null,
	callId	CHAR(36)	not null,
	clientId	CHAR(36)	not null,
	peerConnectionId	CHAR(36)	not null,
	sampleSeq	INTEGER	not null,
	ssrc	BIGINT	not null,
	audioLevel	REAL,
	averageRtcpInterval	REAL,
	burstDiscardCount	INTEGER,
	burstDiscardRate	REAL,
	burstLossCount	INTEGER,
	burstLossRate	REAL,
	burstPacketsDiscarded	INTEGER,
	burstPacketsLost	INTEGER,
	bytesDiscardedOnSend	BIGINT,
	bytesSent	BIGINT,
	channels	INTEGER,
	clockRate	INTEGER,
	echoReturnLoss	REAL,
	echoReturnLossEnhancement	REAL,
	encoderImplementation	VARCHAR(65535),
	ended	BOOLEAN,
	fecPacketsSent	INTEGER,
	fractionLost	REAL,
	gapDiscardRate	REAL,
	gapLossRate	REAL,
	headerBytesSent	BIGINT,
	jitter	REAL,
	label	VARCHAR(65535),
	lastPacketSentTimestamp	BIGINT,
	marker	VARCHAR(65535),
	mimeType	VARCHAR(65535),
	nackCount	INTEGER,
	packetsDiscarded	INTEGER,
	packetsDiscardedOnSend	INTEGER,
	packetsLost	INTEGER,
	packetsReceived	INTEGER,
	packetsRepaired	INTEGER,
	packetsSent	INTEGER,
	payloadType	INTEGER,
	perDscpPacketsSent	INTEGER,
	relayedSource	BOOLEAN,
	reportsReceived	INTEGER,
	retransmittedBytesSent	BIGINT,
	retransmittedPacketsSent	INTEGER,
	rid	VARCHAR(65535),
	roomId	VARCHAR(255),
	roundTripTime	REAL,
	roundTripTimeMeasurements	INTEGER,
	samplesEncodedWithCelt	INTEGER,
	samplesEncodedWithSilk	INTEGER,
	sdpFmtpLine	VARCHAR(65535),
	sfuStreamId	CHAR(36),
	targetBitrate	INTEGER,
	totalAudioEnergy	REAL,
	totalEncodedBytesTarget	BIGINT,
	totalPacketSendDelay	REAL,
	totalRoundTripTime	REAL,
	totalSamplesDuration	REAL,
	totalSamplesSent	INTEGER,
	trackId	CHAR(36),
	userId	VARCHAR(255),
	voiceActivityFlag	BOOLEAN,
)