create table  IF NOT EXISTS outbound_audio_track_report (
	serviceid	VARCHAR(255)	not null,
	mediaunitid	VARCHAR(255)	not null,
	timestamp	BIGINT	not null,
	callid	CHAR(36)	not null,
	clientid	CHAR(36)	not null,
	peerconnectionid	CHAR(36)	not null,
	sampleseq	INTEGER	not null,
	ssrc	BIGINT	not null,
	active	BOOLEAN,
	audiolevel	REAL,
	averagertcpinterval	REAL,
	bytessent	BIGINT,
	droppedsamplesduration	REAL,
	droppedsamplesevents	INTEGER,
	echoreturnloss	REAL,
	echoreturnlossenhancement	REAL,
	encoderimplementation	VARCHAR(65535),
	fractionlost	REAL,
	headerbytessent	BIGINT,
	jitter	REAL,
	label	VARCHAR(65535),
	marker	VARCHAR(65535),
	nackcount	INTEGER,
	packetslost	INTEGER,
	packetsreceived	INTEGER,
	packetssent	INTEGER,
	relayedsource	BOOLEAN,
	retransmittedbytessent	BIGINT,
	retransmittedpacketssent	INTEGER,
	rid	VARCHAR(65535),
	roomid	VARCHAR(255),
	roundtriptime	REAL,
	roundtriptimemeasurements	INTEGER,
	sfustreamid	CHAR(36),
	targetbitrate	INTEGER,
	totalaudioenergy	REAL,
	totalcapturedelay	REAL,
	totalencodedbytestarget	BIGINT,
	totalpacketsenddelay	REAL,
	totalroundtriptime	REAL,
	totalsamplescaptured	REAL,
	totalsamplesduration	REAL,
	trackid	CHAR(36),
	userid	VARCHAR(255)
) diststyle even;
ALTER TABLE outbound_audio_track_report ALTER diststyle KEY DISTKEY serviceid;
ALTER TABLE outbound_audio_track_report ALTER COMPOUND SORTKEY (callid, clientid, peerconnectionid, sfustreamid, trackid);