create table  IF NOT EXISTS SfuSctpStreamReport (
	serviceId	VARCHAR(255)	not null,
	mediaUnitId	VARCHAR(255)	not null,
	sfuId	CHAR(36)	not null,
	timestamp	BIGINT	not null,
	transportId	CHAR(36)	not null,
	streamId	CHAR(36)	not null,
	bytesReceived	BIGINT,
	bytesSent	BIGINT,
	callId	CHAR(36),
	internal	BOOLEAN,
	label	VARCHAR(65535),
	marker	VARCHAR(65535),
	messageReceived	INTEGER,
	messageSent	INTEGER,
	protocol	VARCHAR(255),
	roomId	VARCHAR(255),
	sctpCongestionWindow	REAL,
	sctpMtu	INTEGER,
	sctpReceiverWindow	REAL,
	sctpSmoothedRoundTripTime	REAL,
	sctpUnackData	INTEGER,
)