create table  IF NOT EXISTS SfuOutboundRtpPadReport (
	serviceId	VARCHAR(255)	not null,
	mediaUnitId	VARCHAR(255)	not null,
	sfuId	CHAR(36)	not null,
	timestamp	BIGINT	not null,
	transportId	CHAR(36)	not null,
	sfuStreamId	CHAR(36)	not null,
	sfuSinkId	CHAR(36)	not null,
	rtpPadId	VARCHAR(255)	not null,
	ssrc	BIGINT	not null,
	bytesSent	BIGINT,
	callId	CHAR(36),
	clientId	CHAR(36),
	clockRate	INTEGER,
	fecPacketsDiscarded	INTEGER,
	fecPacketsSent	INTEGER,
	firCount	INTEGER,
	framesEncoded	INTEGER,
	framesSent	INTEGER,
	internal	BOOLEAN,
	keyFramesEncoded	INTEGER,
	marker	VARCHAR(65535),
	mediaType	VARCHAR(65535),
	mimeType	VARCHAR(65535),
	nackCount	INTEGER,
	packetsDiscarded	INTEGER,
	packetsDuplicated	INTEGER,
	packetsFailedEncryption	INTEGER,
	packetsLost	INTEGER,
	packetsRetransmitted	INTEGER,
	packetsSent	INTEGER,
	payloadType	INTEGER,
	pliCount	INTEGER,
	rid	VARCHAR(65535),
	roundTripTime	REAL,
	rtcpRrReceived	INTEGER,
	rtcpSrSent	INTEGER,
	rtxPacketsDiscarded	INTEGER,
	rtxPacketsSent	INTEGER,
	rtxSsrc	BIGINT,
	sdpFmtpLine	VARCHAR(65535),
	sliCount	INTEGER,
	targetBitrate	INTEGER,
	trackId	CHAR(36),
	voiceActivityFlag	BOOLEAN,
)