create table  IF NOT EXISTS SFUTransportReport (
	serviceId	VARCHAR(255)	not null,
	mediaUnitId	VARCHAR(255)	not null,
	sfuId	CHAR(36)	not null,
	timestamp	BIGINT	not null,
	transportId	CHAR(36)	not null,
	callId	CHAR(36),
	dtlsState	VARCHAR(255),
	iceRole	VARCHAR(65535),
	iceState	VARCHAR(255),
	internal	BOOLEAN,
	localAddress	VARCHAR(65535),
	localPort	INTEGER,
	marker	VARCHAR(65535),
	protocol	VARCHAR(255),
	remoteAddress	VARCHAR(65535),
	remotePort	INTEGER,
	roomId	VARCHAR(255),
	rtpBytesReceived	BIGINT,
	rtpBytesSent	BIGINT,
	rtpPacketsLost	INTEGER,
	rtpPacketsReceived	INTEGER,
	rtpPacketsSent	INTEGER,
	rtxBytesReceived	BIGINT,
	rtxBytesSent	BIGINT,
	rtxPacketsDiscarded	INTEGER,
	rtxPacketsLost	INTEGER,
	rtxPacketsReceived	INTEGER,
	rtxPacketsSent	INTEGER,
	sctpBytesReceived	BIGINT,
	sctpBytesSent	BIGINT,
	sctpPacketsReceived	INTEGER,
	sctpPacketsSent	INTEGER,
	sctpState	VARCHAR(255),
)