create table  IF NOT EXISTS SfuInboundRtpPadReport (
	serviceId	VARCHAR(255)	not null,
	mediaUnitId	VARCHAR(255)	not null,
	sfuId	CHAR(36)	not null,
	timestamp	BIGINT	not null,
	transportId	CHAR(36)	not null,
	sfuStreamId	CHAR(36)	not null,
	rtpPadId	VARCHAR(255)	not null,
	ssrc	BIGINT	not null,
	bytesReceived	BIGINT,
	callId	CHAR(36),
	clientId	CHAR(36),
	clockRate	INTEGER,
	fecPacketsDiscarded	INTEGER,
	fecPacketsReceived	INTEGER,
	firCount	INTEGER,
	fractionLost	REAL,
	framesDecoded	INTEGER,
	framesReceived	INTEGER,
	internal	BOOLEAN,
	jitter	REAL,
	keyFramesDecoded	INTEGER,
	marker	VARCHAR(65535),
	mediaType	VARCHAR(65535),
	mimeType	VARCHAR(65535),
	nackCount	INTEGER,
	packetsDiscarded	INTEGER,
	packetsDuplicated	INTEGER,
	packetsFailedDecryption	INTEGER,
	packetsLost	INTEGER,
	packetsReceived	INTEGER,
	packetsRepaired	INTEGER,
	payloadType	INTEGER,
	pliCount	INTEGER,
	remoteRtpPadId	VARCHAR(255),
	remoteSfuId	VARCHAR(255),
	remoteSinkId	VARCHAR(255),
	remoteTransportId	VARCHAR(255),
	rid	VARCHAR(65535),
	roundTripTime	REAL,
	rtcpRrSent	INTEGER,
	rtcpSrReceived	INTEGER,
	rtxPacketsDiscarded	INTEGER,
	rtxPacketsReceived	INTEGER,
	rtxSsrc	BIGINT,
	sdpFmtpLine	VARCHAR(65535),
	sliCount	INTEGER,
	targetBitrate	INTEGER,
	trackId	CHAR(36),
	voiceActivityFlag	BOOLEAN,
)