export interface ClientTransportReport {
	serviceId: string;
	mediaUnitId: string;
	marker?: null | undefined | string;
	timestamp: number;
	callId: string;
	roomId?: null | undefined | string;
	clientId: string;
	userId?: null | undefined | string;
	peerConnectionId: string;
	label?: null | undefined | string;
	packetsSent?: null | undefined | number;
	packetsReceived?: null | undefined | number;
	bytesSent?: null | undefined | number;
	bytesReceived?: null | undefined | number;
	iceRole?: null | undefined | string;
	iceLocalUsernameFragment?: null | undefined | string;
	dtlsState?: null | undefined | string;
	iceTransportState?: null | undefined | string;
	tlsVersion?: null | undefined | string;
	dtlsCipher?: null | undefined | string;
	srtpCipher?: null | undefined | string;
	tlsGroup?: null | undefined | string;
	selectedCandidatePairChanges?: null | undefined | number;
	localAddress?: null | undefined | string;
	localPort?: null | undefined | number;
	localProtocol?: null | undefined | string;
	localCandidateType?: null | undefined | string;
	localCandidateICEServerUrl?: null | undefined | string;
	localCandidateRelayProtocol?: null | undefined | string;
	remoteAddress?: null | undefined | string;
	remotePort?: null | undefined | number;
	remoteProtocol?: null | undefined | string;
	remoteCandidateType?: null | undefined | string;
	remoteCandidateICEServerUrl?: null | undefined | string;
	remoteCandidateRelayProtocol?: null | undefined | string;
	candidatePairState?: null | undefined | string;
	candidatePairPacketsSent?: null | undefined | number;
	candidatePairPacketsReceived?: null | undefined | number;
	candidatePairBytesSent?: null | undefined | number;
	candidatePairBytesReceived?: null | undefined | number;
	candidatePairLastPacketSentTimestamp?: null | undefined | number;
	candidatePairLastPacketReceivedTimestamp?: null | undefined | number;
	candidatePairFirstRequestTimestamp?: null | undefined | number;
	candidatePairLastRequestTimestamp?: null | undefined | number;
	candidatePairLastResponseTimestamp?: null | undefined | number;
	candidatePairTotalRoundTripTime?: null | undefined | number;
	candidatePairCurrentRoundTripTime?: null | undefined | number;
	candidatePairAvailableOutgoingBitrate?: null | undefined | number;
	candidatePairAvailableIncomingBitrate?: null | undefined | number;
	candidatePairCircuitBreakerTriggerCount?: null | undefined | number;
	candidatePairRequestsReceived?: null | undefined | number;
	candidatePairRequestsSent?: null | undefined | number;
	candidatePairResponsesReceived?: null | undefined | number;
	candidatePairResponsesSent?: null | undefined | number;
	candidatePairRetransmissionReceived?: null | undefined | number;
	candidatePairRetransmissionSent?: null | undefined | number;
	candidatePairConsentRequestsSent?: null | undefined | number;
	candidatePairConsentExpiredTimestamp?: null | undefined | number;
	candidatePairBytesDiscardedOnSend?: null | undefined | number;
	candidatePairPacketsDiscardedOnSend?: null | undefined | number;
	candidatePairRequestBytesSent?: null | undefined | number;
	candidatePairConsentRequestBytesSent?: null | undefined | number;
	candidatePairResponseBytesSent?: null | undefined | number;
	sctpSmoothedRoundTripTime?: null | undefined | number;
	sctpCongestionWindow?: null | undefined | number;
	sctpReceiverWindow?: null | undefined | number;
	sctpMtu?: null | undefined | number;
	sctpUnackData?: null | undefined | number;
}
