export interface InboundAudioTrackReport {
	serviceId: string;
	mediaUnitId: string;
	marker?: null | undefined | string;
	timestamp: number;
	callId: string;
	roomId?: null | undefined | string;
	clientId: string;
	userId?: null | undefined | string;
	peerConnectionId: string;
	label?: null | undefined | string;
	trackId?: null | undefined | string;
	rtpStreamId?: null | undefined | string;
	remoteTrackId?: null | undefined | string;
	remoteUserId?: null | undefined | string;
	remoteClientId?: null | undefined | string;
	remotePeerConnectionId?: null | undefined | string;
	sampleSeq: number;
	ssrc: number;
	packetsReceived?: null | undefined | number;
	packetsLost?: null | undefined | number;
	jitter?: null | undefined | number;
	packetsDiscarded?: null | undefined | number;
	packetsRepaired?: null | undefined | number;
	burstPacketsLost?: null | undefined | number;
	burstPacketsDiscarded?: null | undefined | number;
	burstLossCount?: null | undefined | number;
	burstDiscardCount?: null | undefined | number;
	burstLossRate?: null | undefined | number;
	burstDiscardRate?: null | undefined | number;
	gapLossRate?: null | undefined | number;
	gapDiscardRate?: null | undefined | number;
	voiceActivityFlag?: null | undefined | boolean;
	lastPacketReceivedTimestamp?: null | undefined | number;
	averageRtcpInterval?: null | undefined | number;
	headerBytesReceived?: null | undefined | number;
	fecPacketsReceived?: null | undefined | number;
	fecPacketsDiscarded?: null | undefined | number;
	bytesReceived?: null | undefined | number;
	packetsFailedDecryption?: null | undefined | number;
	packetsDuplicated?: null | undefined | number;
	perDscpPacketsReceived?: null | undefined | number;
	nackCount?: null | undefined | number;
	totalProcessingDelay?: null | undefined | number;
	estimatedPlayoutTimestamp?: null | undefined | number;
	jitterBufferDelay?: null | undefined | number;
	jitterBufferEmittedCount?: null | undefined | number;
	decoderImplementation?: null | undefined | string;
	packetsSent?: null | undefined | number;
	bytesSent?: null | undefined | number;
	remoteTimestamp?: null | undefined | number;
	reportsSent?: null | undefined | number;
	ended?: null | undefined | boolean;
	payloadType?: null | undefined | number;
	mimeType?: null | undefined | string;
	clockRate?: null | undefined | number;
	channels?: null | undefined | number;
	sdpFmtpLine?: null | undefined | string;
}
