export interface InboundVideoTrackReport {
	serviceId: string;
	mediaUnitId: string;
	marker?: null | undefined | string;
	timestamp: number;
	callId: string;
	roomId?: null | undefined | string;
	clientId: string;
	userId?: null | undefined | string;
	peerConnectionId: string;
	label?: null | undefined | string;
	trackId?: null | undefined | string;
	rtpStreamId?: null | undefined | string;
	remoteTrackId?: null | undefined | string;
	remoteUserId?: null | undefined | string;
	remoteClientId?: null | undefined | string;
	remotePeerConnectionId?: null | undefined | string;
	sampleSeq: number;
	ssrc: number;
	packetsReceived?: null | undefined | number;
	packetsLost?: null | undefined | number;
	jitter?: null | undefined | number;
	packetsDiscarded?: null | undefined | number;
	packetsRepaired?: null | undefined | number;
	burstPacketsLost?: null | undefined | number;
	burstPacketsDiscarded?: null | undefined | number;
	burstLossCount?: null | undefined | number;
	burstDiscardCount?: null | undefined | number;
	burstLossRate?: null | undefined | number;
	burstDiscardRate?: null | undefined | number;
	gapLossRate?: null | undefined | number;
	gapDiscardRate?: null | undefined | number;
	framesDropped?: null | undefined | number;
	partialFramesLost?: null | undefined | number;
	fullFramesLost?: null | undefined | number;
	framesDecoded?: null | undefined | number;
	keyFramesDecoded?: null | undefined | number;
	frameWidth?: null | undefined | number;
	frameHeight?: null | undefined | number;
	frameBitDepth?: null | undefined | number;
	framesPerSecond?: null | undefined | number;
	qpSum?: null | undefined | number;
	totalDecodeTime?: null | undefined | number;
	totalInterFrameDelay?: null | undefined | number;
	totalSquaredInterFrameDelay?: null | undefined | number;
	lastPacketReceivedTimestamp?: null | undefined | number;
	averageRtcpInterval?: null | undefined | number;
	headerBytesReceived?: null | undefined | number;
	fecPacketsReceived?: null | undefined | number;
	fecPacketsDiscarded?: null | undefined | number;
	bytesReceived?: null | undefined | number;
	packetsFailedDecryption?: null | undefined | number;
	packetsDuplicated?: null | undefined | number;
	perDscpPacketsReceived?: null | undefined | number;
	firCount?: null | undefined | number;
	pliCount?: null | undefined | number;
	nackCount?: null | undefined | number;
	sliCount?: null | undefined | number;
	totalProcessingDelay?: null | undefined | number;
	estimatedPlayoutTimestamp?: null | undefined | number;
	jitterBufferDelay?: null | undefined | number;
	jitterBufferEmittedCount?: null | undefined | number;
	framesReceived?: null | undefined | number;
	decoderImplementation?: null | undefined | string;
	packetsSent?: null | undefined | number;
	bytesSent?: null | undefined | number;
	remoteTimestamp?: null | undefined | number;
	reportsSent?: null | undefined | number;
	ended?: null | undefined | boolean;
	payloadType?: null | undefined | number;
	mimeType?: null | undefined | string;
	clockRate?: null | undefined | number;
	sdpFmtpLine?: null | undefined | string;
}
