export interface OutboundAudioTrackReport {
	serviceId: string;
	mediaUnitId: string;
	marker?: null | undefined | string;
	timestamp: number;
	callId: string;
	roomId?: null | undefined | string;
	clientId: string;
	userId?: null | undefined | string;
	peerConnectionId: string;
	label?: null | undefined | string;
	trackId?: null | undefined | string;
	rtpStreamId?: null | undefined | string;
	sampleSeq: number;
	ssrc: number;
	packetsSent?: null | undefined | number;
	bytesSent?: null | undefined | number;
	rid?: null | undefined | string;
	lastPacketSentTimestamp?: null | undefined | number;
	headerBytesSent?: null | undefined | number;
	packetsDiscardedOnSend?: null | undefined | number;
	bytesDiscardedOnSend?: null | undefined | number;
	fecPacketsSent?: null | undefined | number;
	retransmittedPacketsSent?: null | undefined | number;
	retransmittedBytesSent?: null | undefined | number;
	targetBitrate?: null | undefined | number;
	totalEncodedBytesTarget?: null | undefined | number;
	totalSamplesSent?: null | undefined | number;
	samplesEncodedWithSilk?: null | undefined | number;
	samplesEncodedWithCelt?: null | undefined | number;
	voiceActivityFlag?: null | undefined | boolean;
	totalPacketSendDelay?: null | undefined | number;
	averageRtcpInterval?: null | undefined | number;
	perDscpPacketsSent?: null | undefined | number;
	nackCount?: null | undefined | number;
	encoderImplementation?: null | undefined | string;
	packetsReceived?: null | undefined | number;
	packetsLost?: null | undefined | number;
	jitter?: null | undefined | number;
	packetsDiscarded?: null | undefined | number;
	packetsRepaired?: null | undefined | number;
	burstPacketsLost?: null | undefined | number;
	burstPacketsDiscarded?: null | undefined | number;
	burstLossCount?: null | undefined | number;
	burstDiscardCount?: null | undefined | number;
	burstLossRate?: null | undefined | number;
	burstDiscardRate?: null | undefined | number;
	gapLossRate?: null | undefined | number;
	gapDiscardRate?: null | undefined | number;
	roundTripTime?: null | undefined | number;
	totalRoundTripTime?: null | undefined | number;
	fractionLost?: null | undefined | number;
	reportsReceived?: null | undefined | number;
	roundTripTimeMeasurements?: null | undefined | number;
	relayedSource?: null | undefined | boolean;
	audioLevel?: null | undefined | number;
	totalAudioEnergy?: null | undefined | number;
	totalSamplesDuration?: null | undefined | number;
	echoReturnLoss?: null | undefined | number;
	echoReturnLossEnhancement?: null | undefined | number;
	ended?: null | undefined | boolean;
	payloadType?: null | undefined | number;
	mimeType?: null | undefined | string;
	clockRate?: null | undefined | number;
	channels?: null | undefined | number;
	sdpFmtpLine?: null | undefined | string;
}
