create table  IF NOT EXISTS CallMetaReport (
	serviceId	VARCHAR(255)	not null,
	timestamp	BIGINT	not null,
	mediaUnitId	VARCHAR(255),
	marker	VARCHAR(65535),
	callId	CHAR(36),
	roomId	VARCHAR(255),
	clientId	CHAR(36),
	userId	VARCHAR(255),
	peerConnectionId	CHAR(36),
	sampleTimestamp	BIGINT,
	sampleSeq	INTEGER,
	type	VARCHAR(65535),
	payload	VARCHAR(65535),
)