create table  IF NOT EXISTS ClientTransportReport (
	serviceId	VARCHAR(255)	not null,
	mediaUnitId	VARCHAR(255)	not null,
	timestamp	BIGINT	not null,
	callId	CHAR(36)	not null,
	clientId	CHAR(36)	not null,
	peerConnectionId	CHAR(36)	not null,
	marker	VARCHAR(65535),
	roomId	VARCHAR(255),
	userId	VARCHAR(255),
	label	VARCHAR(65535),
	packetsSent	INTEGER,
	packetsReceived	INTEGER,
	bytesSent	BIGINT,
	bytesReceived	BIGINT,
	iceRole	VARCHAR(65535),
	iceLocalUsernameFragment	VARCHAR(65535),
	dtlsState	VARCHAR(255),
	iceTransportState	VARCHAR(255),
	tlsVersion	VARCHAR(65535),
	dtlsCipher	VARCHAR(65535),
	srtpCipher	VARCHAR(65535),
	tlsGroup	VARCHAR(65535),
	selectedCandidatePairChanges	INTEGER,
	localAddress	VARCHAR(65535),
	localPort	INTEGER,
	localProtocol	VARCHAR(255),
	localCandidateType	VARCHAR(65535),
	localCandidateICEServerUrl	VARCHAR(65535),
	localCandidateRelayProtocol	VARCHAR(255),
	remoteAddress	VARCHAR(65535),
	remotePort	INTEGER,
	remoteProtocol	VARCHAR(255),
	remoteCandidateType	VARCHAR(65535),
	remoteCandidateICEServerUrl	VARCHAR(65535),
	remoteCandidateRelayProtocol	VARCHAR(255),
	candidatePairState	VARCHAR(255),
	candidatePairPacketsSent	INTEGER,
	candidatePairPacketsReceived	INTEGER,
	candidatePairBytesSent	BIGINT,
	candidatePairBytesReceived	BIGINT,
	candidatePairLastPacketSentTimestamp	BIGINT,
	candidatePairLastPacketReceivedTimestamp	BIGINT,
	candidatePairFirstRequestTimestamp	BIGINT,
	candidatePairLastRequestTimestamp	BIGINT,
	candidatePairLastResponseTimestamp	BIGINT,
	candidatePairTotalRoundTripTime	REAL,
	candidatePairCurrentRoundTripTime	REAL,
	candidatePairAvailableOutgoingBitrate	REAL,
	candidatePairAvailableIncomingBitrate	REAL,
	candidatePairCircuitBreakerTriggerCount	INTEGER,
	candidatePairRequestsReceived	INTEGER,
	candidatePairRequestsSent	INTEGER,
	candidatePairResponsesReceived	INTEGER,
	candidatePairResponsesSent	INTEGER,
	candidatePairRetransmissionReceived	INTEGER,
	candidatePairRetransmissionSent	INTEGER,
	candidatePairConsentRequestsSent	INTEGER,
	candidatePairConsentExpiredTimestamp	BIGINT,
	candidatePairBytesDiscardedOnSend	BIGINT,
	candidatePairPacketsDiscardedOnSend	INTEGER,
	candidatePairRequestBytesSent	BIGINT,
	candidatePairConsentRequestBytesSent	BIGINT,
	candidatePairResponseBytesSent	BIGINT,
	sctpSmoothedRoundTripTime	REAL,
	sctpCongestionWindow	REAL,
	sctpReceiverWindow	REAL,
	sctpMtu	INTEGER,
	sctpUnackData	INTEGER,
)