create table  IF NOT EXISTS ClientDataChannelReport (
	serviceId	VARCHAR(255)	not null,
	mediaUnitId	VARCHAR(255)	not null,
	timestamp	BIGINT	not null,
	callId	CHAR(36)	not null,
	clientId	CHAR(36)	not null,
	peerConnectionId	CHAR(36)	not null,
	sampleSeq	INTEGER	not null,
	marker	VARCHAR(65535),
	roomId	VARCHAR(255),
	userId	VARCHAR(255),
	peerConnectionLabel	VARCHAR(65535),
	label	VARCHAR(65535),
	protocol	VARCHAR(255),
	state	VARCHAR(255),
	messagesSent	INTEGER,
	bytesSent	BIGINT,
	messagesReceived	INTEGER,
	bytesReceived	BIGINT,
)