create table  IF NOT EXISTS InboundAudioTrackReport (
	serviceId	VARCHAR(255)	not null,
	mediaUnitId	VARCHAR(255)	not null,
	timestamp	BIGINT	not null,
	callId	CHAR(36)	not null,
	clientId	CHAR(36)	not null,
	peerConnectionId	CHAR(36)	not null,
	sampleSeq	INTEGER	not null,
	ssrc	BIGINT	not null,
	marker	VARCHAR(65535),
	roomId	VARCHAR(255),
	userId	VARCHAR(255),
	label	VARCHAR(65535),
	trackId	CHAR(36),
	sfuStreamId	CHAR(36),
	sfuSinkId	CHAR(36),
	remoteTrackId	VARCHAR(255),
	remoteUserId	VARCHAR(255),
	remoteClientId	VARCHAR(255),
	remotePeerConnectionId	VARCHAR(255),
	packetsReceived	INTEGER,
	packetsLost	INTEGER,
	jitter	REAL,
	packetsDiscarded	INTEGER,
	packetsRepaired	INTEGER,
	burstPacketsLost	INTEGER,
	burstPacketsDiscarded	INTEGER,
	burstLossCount	INTEGER,
	burstDiscardCount	INTEGER,
	burstLossRate	REAL,
	burstDiscardRate	REAL,
	gapLossRate	REAL,
	gapDiscardRate	REAL,
	voiceActivityFlag	BOOLEAN,
	lastPacketReceivedTimestamp	BIGINT,
	averageRtcpInterval	REAL,
	headerBytesReceived	BIGINT,
	fecPacketsReceived	INTEGER,
	fecPacketsDiscarded	INTEGER,
	bytesReceived	BIGINT,
	packetsFailedDecryption	INTEGER,
	packetsDuplicated	INTEGER,
	perDscpPacketsReceived	INTEGER,
	nackCount	INTEGER,
	totalProcessingDelay	REAL,
	estimatedPlayoutTimestamp	BIGINT,
	jitterBufferDelay	REAL,
	jitterBufferEmittedCount	INTEGER,
	decoderImplementation	VARCHAR(65535),
	packetsSent	INTEGER,
	bytesSent	BIGINT,
	remoteTimestamp	BIGINT,
	reportsSent	INTEGER,
	ended	BOOLEAN,
	payloadType	INTEGER,
	mimeType	VARCHAR(65535),
	clockRate	INTEGER,
	channels	INTEGER,
	sdpFmtpLine	VARCHAR(65535),
)