create table  IF NOT EXISTS OutboundVideoTrackReport (
	serviceId	VARCHAR(255)	not null,
	mediaUnitId	VARCHAR(255)	not null,
	timestamp	BIGINT	not null,
	callId	CHAR(36)	not null,
	clientId	CHAR(36)	not null,
	peerConnectionId	CHAR(36)	not null,
	sampleSeq	INTEGER	not null,
	ssrc	BIGINT	not null,
	marker	VARCHAR(65535),
	roomId	VARCHAR(255),
	userId	VARCHAR(255),
	label	VARCHAR(65535),
	trackId	CHAR(36),
	sfuStreamId	CHAR(36),
	packetsSent	INTEGER,
	bytesSent	BIGINT,
	rid	VARCHAR(65535),
	lastPacketSentTimestamp	BIGINT,
	headerBytesSent	BIGINT,
	packetsDiscardedOnSend	INTEGER,
	bytesDiscardedOnSend	BIGINT,
	fecPacketsSent	INTEGER,
	retransmittedPacketsSent	INTEGER,
	retransmittedBytesSent	BIGINT,
	targetBitrate	INTEGER,
	totalEncodedBytesTarget	BIGINT,
	frameWidth	INTEGER,
	frameHeight	INTEGER,
	frameBitDepth	INTEGER,
	framesPerSecond	REAL,
	framesSent	INTEGER,
	hugeFramesSent	INTEGER,
	framesEncoded	INTEGER,
	keyFramesEncoded	INTEGER,
	framesDiscardedOnSend	INTEGER,
	qpSum	BIGINT,
	totalEncodeTime	REAL,
	totalPacketSendDelay	REAL,
	averageRtcpInterval	REAL,
	qualityLimitationDurationCPU	REAL,
	qualityLimitationDurationNone	REAL,
	qualityLimitationDurationBandwidth	REAL,
	qualityLimitationDurationOther	REAL,
	qualityLimitationReason	VARCHAR(65535),
	qualityLimitationResolutionChanges	INTEGER,
	perDscpPacketsSent	INTEGER,
	nackCount	INTEGER,
	firCount	INTEGER,
	pliCount	INTEGER,
	sliCount	INTEGER,
	encoderImplementation	VARCHAR(65535),
	packetsReceived	INTEGER,
	packetsLost	INTEGER,
	jitter	REAL,
	packetsDiscarded	INTEGER,
	packetsRepaired	INTEGER,
	burstPacketsLost	INTEGER,
	burstPacketsDiscarded	INTEGER,
	burstLossCount	INTEGER,
	burstDiscardCount	INTEGER,
	burstLossRate	REAL,
	burstDiscardRate	REAL,
	gapLossRate	REAL,
	gapDiscardRate	REAL,
	framesDropped	INTEGER,
	partialFramesLost	INTEGER,
	fullFramesLost	INTEGER,
	roundTripTime	REAL,
	totalRoundTripTime	REAL,
	fractionLost	REAL,
	reportsReceived	INTEGER,
	roundTripTimeMeasurements	INTEGER,
	relayedSource	BOOLEAN,
	encodedFrameWidth	INTEGER,
	encodedFrameHeight	INTEGER,
	encodedFrameBitDepth	INTEGER,
	encodedFramesPerSecond	REAL,
	ended	BOOLEAN,
	payloadType	INTEGER,
	mimeType	VARCHAR(65535),
	clockRate	INTEGER,
	channels	INTEGER,
	sdpFmtpLine	VARCHAR(65535),
)