create table  IF NOT EXISTS SfuInboundRtpPadReport (
	serviceId	VARCHAR(255)	not null,
	mediaUnitId	VARCHAR(255)	not null,
	sfuId	CHAR(36)	not null,
	timestamp	BIGINT	not null,
	transportId	CHAR(36)	not null,
	sfuStreamId	CHAR(36)	not null,
	rtpPadId	VARCHAR(255)	not null,
	ssrc	BIGINT	not null,
	marker	VARCHAR(65535),
	internal	BOOLEAN,
	remoteSfuId	VARCHAR(255),
	remoteTransportId	VARCHAR(255),
	remoteSinkId	VARCHAR(255),
	remoteRtpPadId	VARCHAR(255),
	trackId	CHAR(36),
	clientId	CHAR(36),
	callId	CHAR(36),
	mediaType	VARCHAR(65535),
	payloadType	INTEGER,
	mimeType	VARCHAR(65535),
	clockRate	INTEGER,
	sdpFmtpLine	VARCHAR(65535),
	rid	VARCHAR(65535),
	rtxSsrc	BIGINT,
	targetBitrate	INTEGER,
	voiceActivityFlag	BOOLEAN,
	firCount	INTEGER,
	pliCount	INTEGER,
	nackCount	INTEGER,
	sliCount	INTEGER,
	packetsLost	INTEGER,
	packetsReceived	INTEGER,
	packetsDiscarded	INTEGER,
	packetsRepaired	INTEGER,
	packetsFailedDecryption	INTEGER,
	packetsDuplicated	INTEGER,
	fecPacketsReceived	INTEGER,
	fecPacketsDiscarded	INTEGER,
	bytesReceived	BIGINT,
	rtcpSrReceived	INTEGER,
	rtcpRrSent	INTEGER,
	rtxPacketsReceived	INTEGER,
	rtxPacketsDiscarded	INTEGER,
	framesReceived	INTEGER,
	framesDecoded	INTEGER,
	keyFramesDecoded	INTEGER,
	fractionLost	REAL,
	jitter	REAL,
	roundTripTime	REAL,
)