create table  IF NOT EXISTS SfuSctpStreamReport (
	serviceId	VARCHAR(255)	not null,
	mediaUnitId	VARCHAR(255)	not null,
	sfuId	CHAR(36)	not null,
	timestamp	BIGINT	not null,
	transportId	CHAR(36)	not null,
	streamId	CHAR(36)	not null,
	marker	VARCHAR(65535),
	internal	BOOLEAN,
	callId	CHAR(36),
	roomId	VARCHAR(255),
	label	VARCHAR(65535),
	protocol	VARCHAR(255),
	sctpSmoothedRoundTripTime	REAL,
	sctpCongestionWindow	REAL,
	sctpReceiverWindow	REAL,
	sctpMtu	INTEGER,
	sctpUnackData	INTEGER,
	messageReceived	INTEGER,
	messageSent	INTEGER,
	bytesReceived	BIGINT,
	bytesSent	BIGINT,
)