create table  IF NOT EXISTS SfuOutboundRtpPadReport (
	serviceId	VARCHAR(255)	not null,
	mediaUnitId	VARCHAR(255)	not null,
	sfuId	CHAR(36)	not null,
	timestamp	BIGINT	not null,
	transportId	CHAR(36)	not null,
	sfuStreamId	CHAR(36)	not null,
	sfuSinkId	CHAR(36)	not null,
	rtpPadId	VARCHAR(255)	not null,
	ssrc	BIGINT	not null,
	marker	VARCHAR(65535),
	internal	BOOLEAN,
	callId	CHAR(36),
	clientId	CHAR(36),
	trackId	CHAR(36),
	mediaType	VARCHAR(65535),
	payloadType	INTEGER,
	mimeType	VARCHAR(65535),
	clockRate	INTEGER,
	sdpFmtpLine	VARCHAR(65535),
	rid	VARCHAR(65535),
	rtxSsrc	BIGINT,
	targetBitrate	INTEGER,
	voiceActivityFlag	BOOLEAN,
	firCount	INTEGER,
	pliCount	INTEGER,
	nackCount	INTEGER,
	sliCount	INTEGER,
	packetsLost	INTEGER,
	packetsSent	INTEGER,
	packetsDiscarded	INTEGER,
	packetsRetransmitted	INTEGER,
	packetsFailedEncryption	INTEGER,
	packetsDuplicated	INTEGER,
	fecPacketsSent	INTEGER,
	fecPacketsDiscarded	INTEGER,
	bytesSent	BIGINT,
	rtcpSrSent	INTEGER,
	rtcpRrReceived	INTEGER,
	rtxPacketsSent	INTEGER,
	rtxPacketsDiscarded	INTEGER,
	framesSent	INTEGER,
	framesEncoded	INTEGER,
	keyFramesEncoded	INTEGER,
	roundTripTime	REAL,
)