create table  IF NOT EXISTS SFUTransportReport (
	serviceId	VARCHAR(255)	not null,
	mediaUnitId	VARCHAR(255)	not null,
	sfuId	CHAR(36)	not null,
	timestamp	BIGINT	not null,
	transportId	CHAR(36)	not null,
	marker	VARCHAR(65535),
	internal	BOOLEAN,
	callId	CHAR(36),
	roomId	VARCHAR(255),
	dtlsState	VARCHAR(255),
	iceState	VARCHAR(255),
	sctpState	VARCHAR(255),
	iceRole	VARCHAR(65535),
	localAddress	VARCHAR(65535),
	localPort	INTEGER,
	protocol	VARCHAR(255),
	remoteAddress	VARCHAR(65535),
	remotePort	INTEGER,
	rtpBytesReceived	BIGINT,
	rtpBytesSent	BIGINT,
	rtpPacketsReceived	INTEGER,
	rtpPacketsSent	INTEGER,
	rtpPacketsLost	INTEGER,
	rtxBytesReceived	BIGINT,
	rtxBytesSent	BIGINT,
	rtxPacketsReceived	INTEGER,
	rtxPacketsSent	INTEGER,
	rtxPacketsLost	INTEGER,
	rtxPacketsDiscarded	INTEGER,
	sctpBytesReceived	BIGINT,
	sctpBytesSent	BIGINT,
	sctpPacketsReceived	INTEGER,
	sctpPacketsSent	INTEGER,
)