name: Release schemas library for monitors
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      working-directory: ./npm-monitor-lib
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - run: npm install -g yarn
      - name: install packages
        run: yarn
        working-directory: ${{env.working-directory}}

      - name: Setup Custom Contexts
        working-directory: ${{env.working-directory}}
        shell: bash
        run: | 
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
          echo "##[set-output name=version;]$(cat ./package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')"
        id: job_context

      - name: Make snapshot version
        if: steps.job_context.outputs.branch != 'main'
        working-directory: ${{env.working-directory}}
        run: |
          npm version ${{ steps.job_context.outputs.version }}-SNAPSHOT.${{ github.sha }}

      - name: Publish
        working-directory: ${{env.working-directory}}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}