name: Release full schemas library
on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      working-directory: ./npm-lib
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - run: npm install -g yarn
      - name: install packages
        run: yarn
        working-directory: ${{env.working-directory}}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch

      - name: Publish
        if: steps.extract_branch.outputs.branch == 'main'
        working-directory: ${{env.working-directory}}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Snapshot
        if: steps.extract_branch.outputs.branch != 'main'
        working-directory: ${{env.working-directory}}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts --access public --tag SNAPSHOT-${{ github.sha }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}